//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sign2sign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public content()
        {
            this.playlists = new HashSet<playlist>();
        }
    
        public int id { get; set; }
        public Nullable<int> business_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string video { get; set; }
        public Nullable<int> duration { get; set; }
        public string text { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> @public { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string html { get; set; }
    
        public virtual business business { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlist> playlists { get; set; }
    }
}
