//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sign2sign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class played
    {
        public int id { get; set; }
        public Nullable<int> playlist_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> window_id { get; set; }
        public Nullable<int> duration { get; set; }
    
        public virtual playlist playlist { get; set; }
        public virtual window window { get; set; }
    }
}
