//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sign2sign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int id { get; set; }
        public int business_id { get; set; }
        public int categoty_id { get; set; }
        public Nullable<bool> allow { get; set; }
        public Nullable<bool> deny { get; set; }
        public Nullable<double> distance { get; set; }
    
        public virtual business business { get; set; }
        public virtual category category { get; set; }
    }
}
