//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sign2sign.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sign2signEntities : DbContext
    {
        public sign2signEntities()
            : base("name=sign2signEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<business> businesses { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<content> contents { get; set; }
        public virtual DbSet<layout> layouts { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<played> playeds { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<playlist> playlists { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<screen> screens { get; set; }
        public virtual DbSet<window> windows { get; set; }
    }
}
