//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sign2sign.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class window
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public window()
        {
            this.playeds = new HashSet<played>();
        }
    
        public int id { get; set; }
        public Nullable<int> layout_id { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> hieght { get; set; }
        public Nullable<int> posiotion_x { get; set; }
        public Nullable<int> position_y { get; set; }
        public Nullable<int> z_index { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> playlist_id { get; set; }
    
        public virtual layout layout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<played> playeds { get; set; }
        public virtual playlist playlist { get; set; }
    }
}
